# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{metastrano}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Paul Narowski"]
  s.date = %q{2010-02-16}
  s.description = %q{This is a gem that is suppose to help you automate all of your server deployment and project maintenance tasks}
  s.email = %q{jnarowski@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/helpers.rb",
     "lib/metastrano.rb",
     "lib/recipes/apache.rb",
     "lib/recipes/db.rb",
     "lib/recipes/delayed_job.rb",
     "lib/recipes/deploy.rb",
     "lib/recipes/git.rb",
     "lib/recipes/rake.rb",
     "lib/recipes/setup.rb",
     "lib/recipes/symlink.rb",
     "lib/recipes/wordpress.rb",
     "lib/templates/apache.conf.erb",
     "lib/templates/database.yml.erb",
     "lib/templates/gitignore",
     "lib/templates/wordpress.2.8.6.php.erb",
     "test/helper.rb",
     "test/test_metastrano.rb"
  ]
  s.homepage = %q{http://github.com/jnarowski/metastrano}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Capistrno recipes for Passenger, MySQL Etc}
  s.test_files = [
    "test/helper.rb",
     "test/test_metastrano.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<capistrano>, [">= 2.3.0"])
      s.add_development_dependency(%q<erb>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<capistrano>, [">= 2.3.0"])
      s.add_dependency(%q<erb>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<capistrano>, [">= 2.3.0"])
    s.add_dependency(%q<erb>, [">= 0"])
  end
end

